---
title: "R Notebook"
output: html_notebook
---

 

```{r setup and such, echo = F}
library(dplyr); library(ggplot2); library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
rstan_options(threads_per_chain = 1)




```


# Introduction 


# Setup 

```{r simulate data, echo = F}

mu_true <- c(2,2.4)
cv_space <- 0.45
cv_obs <- 0.1
N <- 30
K <- 2 
P <- N*K 
samp = rep(c(1,2),each=N)
SOC <- matrix(0,nrow=K,ncol=N)
SOC2 <- matrix(0,nrow=K,ncol=N)

for(i in 1:K){
SOC[i,] <- rnorm(N,mu_true[i],mu_true[i]*cv_space)
}

hist(SOC[1,])

sim_df <- data.frame(y=c(SOC[1,],SOC[2,]),samp = rep(c(0,1),each=N))
summary(lm(y~samp,sim_df))



pooled_bayes_data <- list(y_obs=c(SOC[1,],SOC[2,]),samp=as.integer(samp),N=N,K=K,P=P)
pooled_bayes_ez <- list(y_obs=c(2,2.9,1.8),N=3,K=30)


```

type M/S error is a big(ger) worry than type I/II. Why so? with type M we risk wildly overpaying. With type S - perversely paying. 

```{r run stan model, echo = F}

getwd()
s1 <- stan(file = "pooled_Bayes.stan", data = pooled_bayes_data, chains = 1, iter = 1000)



```

